### PR TITLE
Update subdirectory structure

### PR DESCRIPTION
**Pull request by ewquon**
I'd like to organize the assessment repo by dataset that we're processing. What I'm envisioning the repo eventually looking like is:
- `SWiFT` _(for data processing/derived quantities)_
- `WFIP2`
- `WFIP3`
- ...
- `perturbation_study` _(for analysis/reporting)_
- `coupling_comparison`
- ...
where the analyses would depend on one or more datasets that we've already processed.

I wouldn't be opposed to putting SWIFT, WFIP*, etc into a subdirectory (e.g., `data/*`, `datsets/*`, or `data_processing/*`) and/or the studies into a subdirectory (e.g., `studies/perturbation_methods`, `studies/coupling_comparison`, etc). @amydecastro and @jsauer-NCAR, thoughts?

### CODE REVIEW

**Comment by jsauer-NCAR** [comment]
A datasets directory holding various tools for data pre-processing of SWiFT, WFIP2, etc. sounds sensible. If the actual tools used for the assessment studies really reside in mmctools, then the overarching studies directory make sense as well.  I still worry about all this repository engineering without have anyone yet exercising the functionality therein as of yet besides the authors themselves.  We need MMC members to start picking these up and trying to use them ASAP.

**Comment by ewquon** [comment]
@jsauer-NCAR I think of the notebooks in this repo not as "tools" but as illustrations of use cases of the code in `mmctools`. We should not be developing new tools or capabilities here. Perhaps you could loop me into the next conversation you have with Jeff (who has yet to join the organization) about assessing his perturbation study results.

**Comment by ewquon** [comment]
Holding off on this merge until we get the other PRs sorted out.

**Comment by ewquon** [comment]
@jsauer-NCAR and @amydecastro, see https://github.com/ewquon/assessment/tree/hotfix/reorg_dirs for the new assessment directory structure. Summary:
- I've moved the site-specific data analyses into a "datasets" subdirectory.
- I've create a new "studies" subdirectory for the studies we're working on in FY19.
- I've gotten rid of the old unused notebooks (`2_calculations.ipynb` and `3_analysis.ipynb`) because they were only placeholders and are no longer useful at this point. I've moved `1_data_processing.ipynb` into a new "examples" subdirectory.

**Comment by jsauer-NCAR** [comment]
Looks like a much improved organization scheme to me.  Is there more you will do before merging this PR?

**Comment by ewquon** [comment]
I'm working on cleaning up `1_data_processing.ipynb` at the moment, but that can (should) come as a later PR. Still need to work with Matt M to debug dap-py before that's ready. 

Here's my overall vision, any additional feedback is welcome:
a2e-mmc_repo_structure
I can also add it to the PR if you think it will be useful.

**Comment by jsauer-NCAR** [comment]
I like the vision and the diagram is very handy to better understand the vision.  Is there any way to incorporate third-party repositories into the diagram (e.g. dap-py, or Jeff's new ERF (WRF-Energy) project)?  I think it would be valuable to put this diagram into this PR and let it evolve over time as your vision is executed and undergoes refinements.  Really good step here, well done.

**Pull request merged**
