### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by amydecastro**
I'd like to add these two notebooks to the a2e-mmc dev branch.

### CODE REVIEW

**Review by ewquon — APPROVED** [review]
Very well-documented notebooks. I would like to see `write_to_netCDF()` moved to `mmctools/measurements/metmast.py` so that you can import the same functionality for both notebooks with `from measurements.metmast import write_to_netCDF`.

**Comment by ewquon** [comment]
@amydecastro should we go ahead and merge this, or did you want to add a `write_to_netCDF()` function to mmctools?

**Comment by jsauer-NCAR** [comment]
I totally agree that write_to_netCDF() should be moved to mmctools.

**Comment by ewquon** [comment]
@amydecastro The last cell of `MMC-Data_met.z12` has a hanging ')' and does not execute.

**Comment by ewquon** [comment]
@amydecastro To expedite this, I've created the `datawriters` module in `a2e.mmctools`. You can replace your write_to_netCDF definition cell with:

`from mmctools.datawriters import write_to_netCDF`

I've successfully tested this with your MMC-Data_met.z12 notebook.

**Comment by amydecastro** [comment]
@ewquon I adjusted these two notebooks so that they use datawriters.py instead of a definition within the notebooks. Thanks again for setting up datawriters.py! Let's merge this?

**Pull request merged**
