### PR TITLE
Update TTU radar processing

### PR DESCRIPTION
**Pull request by ewquon**
- Make code compatible with https://github.com/a2e-mmc/mmctools/pull/32
- Use data generated by `datasets/SWiFT/process_TTU_tower.ipynb` (tracked in this repo) instead of previously generated data
- Verified agreement between previous data and data output from `process_TTU_tower.ipynb`
- Verified timestamp alignment between tower and radar data. 
- Standardize names for wind speed/direction
- Update (most) plotting routines to use `mmctools.plotting` library

### CODE REVIEW

**Comment by ewquon** [comment]
@DriesAllaerts this is still a WIP, let's discuss the SNR analysis today and finalize the plotting code. Also, see the ReviewNB link above to see jupyter notebook diff (instead of the diff between the raw json code)!

**Comment by DriesAllaerts** [comment]
I noticed there are different ways to compute the wind direction based on the `u` and `v` components. My preferred approach is to use the following single line of code instead of having to update negative wind directions in a second step. 
`wdir = 180. + np.degrees(np.arctan2(u,v))`

Maybe computing wind speed and wind direction could be added as helper functions, in part to help avoid erroneous calculation of wind direction.

**Comment by ewquon** [comment]
@DriesAllaerts, I've implemented this in https://github.com/a2e-mmc/mmctools/pull/34. Ironically, using the new data eliminates the need to calculate wspd/wdir within `process_TTU_radar.ipynb`. So instead, I've updated `process_TTU_tower.ipynb` to use the new function. 

I've tested it for cases with overwriting existing wspd/wdir, as well as with different wind component names.

**Comment by ewquon** [comment]
@DriesAllaerts, at the end of the day here's what the natural-neighbor inter/extrapolated data for all obs look like:
image

Starting from the two radar scans (with SNR cutoff at -22.5 dB) and tower data:
image

Let me know if you think it needs some additional postprocessing, particularly around 2013-11-09 0600--1200, for z > 1250 m. 

Also, let me know what format you'd prefer the output data in for input to `mmctools.coupling.internal`.

**Comment by DriesAllaerts** [comment]
@ewquon Nice work on automating the qc. I can definitely work with this data, so unless you still have crazy ideas to improve the postprocessing I think it is fine. In terms of output data, I'm used to reading in .csv, but I should be able to use .npz as well with a little help.

One smal request: In cell 37 can you use the actual SNR_cutoff for the width of the grey zone in the figure instead of the hardcoded value of -25?

**Review by DriesAllaerts — CHANGES_REQUESTED** [review]
For process_TTU_tower:
1. Is there a reason why Tv and thetav is no longer computed?
2. wspd, wdit, theta, ... are all computed within calc_stats but no really turbulence statistics. Maybe for clarity split up in calc_mean_quantities and calc_stats
3. Is there a use-case for the heat flux based on (virtual) potential temperature thetav'w' instead of Ts'w'?

For process_TTU_radar:
1. Shift output timestamp for NNinterp back to "cell-centered" values

**Comment by ewquon** [comment]
@DriesAllaerts, I will add in the additional quantities of interest.

**Comment by ewquon** [comment]
@DriesAllaerts, a couple comments:
1. I've added calculations for $\theta$ and $\theta_s$, using https://github.com/a2e-mmc/mmctools/pull/37, as well as $\overline{\theta_s'w'}$. From `TTU_tower_heatflux_stability.ipynb`, we can see that $T_s$ is very nearly the same as $T_v$ in this case, so I opted not to calculate additional ~identical quantities involving $T_v$, which would have required additional assumptions.  
2. I've shifted the gridded time-height data (output from the natural-neighbor interpolation) to the "cell centers". Note that in addition to shifting the time by 5 min, I also shifted the heights by dz/2 = 10 m.

**Comment by ewquon** [comment]
Results should now be satisfactory for the coupling comparison study.

**Pull request merged**
