### PR TITLE
Addition of PMIC-mesoscale assessment example notebook.

### PR DESCRIPTION
**Pull request by jsauer-NCAR**
An example notebook for basic sanity check of WRF d01 (mesoscale) results. This notebook specifically looks at how the mesoscale prescribed forcing conditions (a2e-mmc/WRF-setups/WRF-setups/SWiFT_20131108_PertMethodsGroup/CBL_18Z-20Z/[namelist.input and input_sounding] manifest in targeting observations for that particular period of interest.

Profiles-PMIC1_d01_test

### CODE REVIEW

**Comment by jmirocha** [comment]
<p>Successfully ran notebook on my system</p>

**Review by jmirocha — APPROVED** [review]
I successfully ran this notebook on my data

**Comment by ewquon** [comment]
"Don't let perfection be the enemy of progress" as they say. My current changes (and TODO notes) have been added in https://github.com/jsauer-NCAR/assessment/pull/2. Please review and then merge.

**Review by ewquon — CHANGES_REQUESTED** [review]
See https://github.com/jsauer-NCAR/assessment/pull/2

**Comment by jsauer-NCAR** [comment]
> See [jsauer-NCAR#2](https://github.com/jsauer-NCAR/assessment/pull/2)

is a request to merge into the wrong feature branch of my jsauer-NCAR/assessment fork.

**Comment by jsauer-NCAR** [comment]
Ok I pulled Eliot's changes which referred in the end to jsauer-NCAR#3, and I did the 'use wrfout_seriesReader, TODO item.' I also added a save of the assessment metrics (just the whole xarray dataset with QOIs in this case) to the end of the notebook.

**Review by ewquon — APPROVED** [review]

**Review by ewquon — APPROVED** [review]

**Pull request merged**
