### PR TITLE
Add GitHub getting started tutorial

### PR DESCRIPTION
**Pull request by ewquon**
All: Feel free to suggest edits for clarity!

### CODE REVIEW

**Comment by ewquon** [comment]
Rendered version: https://github.com/a2e-mmc/assessment/blob/358f239e9cf3fbae2607c35ada9d3cdd6a7d5152/developers/github_tutorial.md

Comment on the "Files changed" tab by clicking the + sign next to the line in question.

**Review by jsauer-NCAR — CHANGES_REQUESTED** [review]
Tutorial is great. 
Maybe just add a call out to be careful (as Jeff found out) with the suggested add/commit shortcut step " git commit -a -m 'Make some change' "? A note that 'commit -a' will only automatically add and commit currently tracked files. One cannot avoid using git add for new files to be included in repo tracking....

**Comment by ewquon** [comment]
@jsauer-NCAR, okay, I've added the requested comment. Let me know if there's anything else...

Also, I was thinking of taking this "github getting started" folder and just putting it into a new repo, e.g., a2e-mmc/developers. I expect this to be much more static, so it can just live in the master branch (and users can go directly to the site and land on the guide on the front page). Thoughts?

**Review by jsauer-NCAR — APPROVED** [review]
Resolved, and the -m advice to boot.  Good idea to make finding the tutorial as easy and obvious as possible.

**Comment by ewquon** [comment]
Created new repo:
https://github.com/a2e-mmc/developer/commit/eef82aa0a934c571dc967c16e3e32c5948c66f07

**Comment by ewquon** [comment]
Okay, going to commit only a couple of minor changes:
- Update .gitignore to help keep the git working tree clean
- Update assessment repo org chart, and add associated mermaid.js flowchart

All tutorial files (i.e., previous contents of the 'developer' directory) have been moved to the new repo https://github.com/a2e-mmc/developer

**Pull request merged**
