### PR TITLE
Add WRF-SOWFA conversion notebook for offshore case

### PR DESCRIPTION
**Pull request by rthedin**
Notebook containing SOWFA-ready inputs for the microscale simulations of the offshore challenge case

### CODE REVIEW

**Comment by ewquon** [comment]
This looks great @rthedin! Where does `FINO1_d03_full.nc` come from, though?

**Comment by rthedin** [comment]
It comes from a WRF run; possibly involving some post-processing. I got that from @phawbeck, so he may be able to give more details.

**Comment by hawbecker** [comment]
I had an issue with my data from the FINO runs... it was stored on scratch and not moved before the purge. Let me try to dig to find what this might be. Can you do an "ncdump -h" on the file, or point me to it on Eagle?

**Comment by rthedin** [comment]
The file is at `/projects/mmc/rthedin/OpenFOAM/rthedin-6/run/offshoreCases/FINO1_d03_full.nc`

**Comment by hawbecker** [comment]
Looks like the file is just the FINO1 virtual tower data read in via the Tower class on domain 3. If you ncdump -h, the only attribute shows the simulation it came from (ERA5, pbl=MYJ, Charnock roughness, ERA5 SST, no sst_skin, 3 domains in run). I used to think it was worth adding the attributes from the WRF run to the tower data, but since the tower data is not necessarily co-located with the wrfout files, it would be hard to do universally.

**Pull request merged**
