### PR TITLE
Analysis of TTU tower TKE

### PR DESCRIPTION
**Pull request by DriesAllaerts**

### CODE REVIEW

**Review by ewquon — APPROVED** [review]
@DriesAllaerts Thanks for putting this together. This will be good for disseminating and archiving our findings about the upper-level sonics.

**Comment by ewquon** [comment]
FYI @jsauer-NCAR. Summary of findings at the top of the notebook. If you don't have any comments or suggestions, I'll merge this in early next week.

**Comment by jsauer-NCAR** [comment]
<p>I like the notebook as an example using the assessment utilities to plot up what could be inconsistent behavior from the 158m and 200m tower sonics.</p><p> </p><p>While I like the notebook format and as an illustrative example, I don't quite see what your intentions are for it scientifically.  No explanation of the strange data, or corroboration against other data.  This anomaly is outside of the targeted comparison time-windows for coupling methods and perturbation methods studies. Do you intend for more here, or just a nice example usage of the utilities?</p><p> </p><p>If the latter, great. If the former, it could use more assessment steps and explanations.</p><p> </p>

**Comment by ewquon** [comment]
@jsauer-NCAR my intention for getting Dries to put this together was to have a record of some of the fluctuating quantities on the tower being unreliable. To caution other researchers about using this data set at that height during that particular time period. It is a nice bonus that it is a short and sweet demo of some of the mmctools capabilities. As far as I know, there is no way to ascertain what the true values are since there are no other high-frequency measurements in the area at that height. What do you recommend we do or say at the top of the notebook?

**Comment by jsauer-NCAR** [comment]
<p>@ewquon.  Of course all observation data potentially has some periods that are unreliable/inconsistent if one looks for it, but fair enough to point this one out since Dries has identified it. Maybe at the top, just do as you suggest and caution others using this dataset not to simply assume data is QC'd and void of inconsistencies, since some seemingly inconsistent periods such as this have been identified, but not removed. I wonder what the radar says for that period of time w.r.t the windspeed magnitudes.  Maybe others could look at other sources of data (if any exist) like the radar to find evidence of whether or not these velocity magnitudes and fluctuations may have been real.  With a little cautionary note in the summary up top as you suggest, I think this is a valuable addition and suitable to merge.</p>

**Comment by ewquon** [comment]
@DriesAllaerts or I will update the notebook header/summary next week (I’m out of town this weekend). We should point to the process_TTU_radar.ipynb to illustrate the agreement between radar and met mast around 200m for 10-min means.

Thanks,
Eliot

Sent from my iPhone

On Aug 24, 2019, at 11:28 AM, Jeremy Sauer <notifications@github.com<mailto:notifications@github.com>> wrote:


@ewquon<https://github.com/ewquon>. Of course all observation data potentially has some periods that are unreliable/inconsistent if one looks for it, but fair enough to point this one out since Dries has identified it. Maybe at the top, just do as you suggest and caution others using this dataset not to simply assume data is QC'd and void of inconsistencies, since some seemingly inconsistent periods such as this have been identified, but not removed. I wonder what the radar says for that period of time w.r.t the windspeed magnitudes. Maybe others could look at other sources of data (if any exist) like the radar to find evidence of whether or not these velocity magnitudes and fluctuations may have been real. With a little cautionary note in the summary up top as you suggest, I think this is a valuable addition and suitable to merge.

**Pull request merged**
