### PR TITLE
Add basic data processing examples

### PR DESCRIPTION
**Pull request by ewquon**
Illustrate some basic functionality from [`mmctools`](https://github.com/a2e-mmc/mmctools) for data processing and analysis:
- `mmctools.dataloaders.read_*`
- `mmctools.measurements.radar`
- `mmctools.plotting`

Also, demonstrate the [`dap-py`](https://github.com/a2edap/dap-py) interface to the [Data Archive and Portal](https://a2e.energy.gov/about/dap) (DAP).

### CODE REVIEW

**Review by DriesAllaerts — COMMENTED** [review]
Very useful and well documented examples! Thanks for putting this together @ewquon

**Comment by cmkaul** [comment]
@ewquon, thanks for these examples!
I attempted to run through all the example notebooks (manually downloading data sets and running on my desktop Mac), but in all cases, received an error when attempting to read the files. For example, for the 001-DAP_data_processing notebook:
```
Reading /Users/kaul025/DAP_datasets/wfip2.radar.z04.b0/radar.z04.b0.20161121.000000.winds.txt
 while reading /Users/kaul025/DAP_datasets/wfip2.radar.z04.b0/radar.z04.b0.20161121.000000.winds.txt
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<timed exec> in <module>

~/OneDrive - PNNL/Eliot_Notebooks/mmctools/dataloaders.py in read_dir(dpath, file_filter, reader, sort, verbose, **kwargs)
    100         except reader_exceptions as err:
    101             print(err,'while reading',fpath)
--> 102         dataframes.append(df)
    103     if len(dataframes) == 0:
    104         print('No dataframes were read!')

UnboundLocalError: local variable 'df' referenced before assignment
```
I don't see any obvious problems-I seem to have the paths to the data correct and the data files themselves look okay.

Any suggestions? Thanks!

**Comment by cmkaul** [comment]
I also found it necessary to add a couple lines to each notebook to be able to import the modules from mmctools. i.e.,
```
import sys
module_path = '/Users/kaul025/OneDrive - PNNL/Eliot_Notebooks'
if module_path not in sys.path:
    sys.path.append(module_path)
```

**Comment by ewquon** [comment]
Hi @cmkaul,

I've added your proposed change to all three example notebooks.

Regarding the error you're getting, I should have mentioned that there are a couple of companion pull requests to the mmctools repo that *should* address these issues:
- https://github.com/a2e-mmc/mmctools/pull/31 
- https://github.com/a2e-mmc/mmctools/pull/32

I was waiting for these notebooks to be tested and merged before accepting those changes.

To test the notebooks, please clone my repository and checkout the dev branch, which contains both of those updates:
https://github.com/ewquon/mmctools/tree/dev

**Comment by cmkaul** [comment]
With the updates to mmctools, these notebooks work beautifully.  A minor observation: in 001-DAP_data_processing.ipynb, the cell containing these lines of code
```
filelist.sort()
filelist[:5]
```
will return an error if working through the notebook with manually downloaded data. This doesn't seem too consequential as the point of the notebook is to demonstrate the use of dap-py, but I think it could be easily fixed by moving those lines within the try/except/else structure.

**Comment by ewquon** [comment]
@cmkaul, done.

**Review by cmkaul — APPROVED** [review]
Very nice! Thanks for your efforts, @ewquon!

**Comment by ewquon** [comment]
@jsauer-NCAR, any thoughts before I merge?

**Comment by ewquon** [comment]
Going to move forward with this so that I can close the other related PR's.

**Pull request merged**
