### PR TITLE
Initialize coupling comparison study

### PR DESCRIPTION
**Pull request by DriesAllaerts**
Update README.md and add two preprocessing notebooks for internal forcing coupling methods:
- `wrf_to_sowfa`: Generate SOWFA readable input files based on WRF data
- `obs_to_sowfa`: Generate SOWFA readable input files solely based on observations

### CODE REVIEW

**Comment by ewquon** [comment]
I envisioned this PR being a merge of all the coupling resources (including my `coupling.boundary` work) into `assessment/studies/coupling_comparison`. Not just an "initialization". Are you in a hurry to get this in?

**Comment by DriesAllaerts** [comment]
I'm not really in a hurry, but I think it would be safer to gradually add notebooks than wait until all notebooks and functions are finished. Moreover, I need to work on analysis notebooks to share with the team, and I envisioned sharing these through the repository. What about we create a `study/coupling_comparison` branch which we can update while the study is running, and once it is finished we merge it into the dev branch.

**Comment by ewquon** [comment]
@DriesAllaerts, I've created a separate branch per your suggestion and changed the PR to merge into this new `study/coupling_comparison` branch. Should we go ahead and get this merged, and you can submit additional PRs as the study progresses?

**Comment by DriesAllaerts** [comment]
I think this is best way to go forward. Go ahead and merge this PR into the new branch and I'll submit any new updates to this branch.

**Pull request merged**
