### PR TITLE
TTU radar analysis

### PR DESCRIPTION
**Pull request by ewquon**
Developed notebook to provide (microscale) profile assimilation data for @DriesAllaerts. Makes use of `mmctools.dataloaders.read_dir()` and `mmctools.measurements.radar.profiler()`.

Dependencies
- Latest updates to `profiler()` that handle different scan types within a single data file
- QC'd radar data that I created by manually removing outlier points; this should probably be moved to the DAP if/when we all agree that it's a "good" dataset (and/or when we apply more rigorous QC procedures)
- `naturalneighbor` interpolation library, which is the approach typically used to interpolate/extrapolate scattered lidar data observations to a regular grid

### CODE REVIEW

**Comment by ewquon** [comment]
A quick note/tip: to view the file, go to `Files Changed` tab, and it will say that "Large diffs are not rendered by default." If you click the `...` on the right, there is a `View file` link.

**Review by DriesAllaerts — COMMENTED** [review]
The notebook looks good except for the last snippet to save as a csv file. Looks like the code is entered in a text cell but this makes it hard to read and understand.

**Review by DriesAllaerts — COMMENTED** [review]
Can you double check the functionality of the following code?
assert all(~pd.isna(alldata['SPD']))
assert all(~pd.isna(alldata['DIR']))

I found that this approach does not work properly, at least for a pivoted pandas dataframe. Alternatively, you can use pandas built-in functions:
assert ~pd.isna(alldata['SPD']).any()

**Comment by ewquon** [comment]
Thanks for the comments, @DriesAllaerts

**Pull request merged**
