### PR TITLE
Add pandas multi index tutorial

### PR DESCRIPTION
**Pull request by DriesAllaerts**
Working with pandas requires some experience and can be hard to start with. On top of that, using pandas multi-index dataframe represents a second hurdle, and I must say it took me some time to get used to it. However, after an initial learning period, I find that pandas multi-indexing is much more powerful and transparant than single index dataframes. To use pandas multi-index dataframes efficiently, some specific tools are essential and will make your life much easier . To help people that are interested in learning to work with multi-index dataframes, I composed a tutorial on pandas multi-index dataframes and shared the most essential tools and commands I use to work with these structures.

### CODE REVIEW

**Review by ewquon — APPROVED** [review]
I think this is a useful reference for the dataframe manipulations we typically do. @jsauer-NCAR, @amydecastro, @phawbeck please let Dries know how this can be more helpful to people getting started with python/pandas.

**Review by hawbecker — APPROVED** [review]
This tutorial was very clear and helpful. Thanks for putting this together!

**Comment by amydecastro** [comment]
<p>This is exactly what I needed! Thank you!</p>

**Review by amydecastro — APPROVED** [review]

**Review by jsauer-NCAR — APPROVED** [review]
Looks very helpful, thanks for crafting this.

**Pull request merged**
