### PR TITLE
Add study on profile assimilation technique

### PR DESCRIPTION
**Pull request by DriesAllaerts**
Jupyter notebook and file with helper functions to produce figures of the paper, "Large-eddy simulation of a diurnal cycle driven by assimilation of mesoscale time-height profiles",
by Dries Allaerts, Eliot Quon, Caroline Draxl and Matthew Churchfield

### CODE REVIEW

**Comment by ewquon** [comment]
Issue with date time axis formatting (affects Figs. 1, 3, and 4). `UserWarning` noted:
> /home/equon/miniconda3/envs/forge/lib/python3.7/site-packages/ipykernel_launcher.py:32: UserWarning: AutoDateLocator was unable to pick an appropriate interval for this date range. It may be necessary to add an interval value to the AutoDateLocator's intervald dictionary. Defaulting to 12.

**Comment by DriesAllaerts** [comment]
When I run the notebook myself I don't get warnings for Figs. 1 and 4. Fig. 3 indeed gave a warning, adjusting the arguments of the AutoDateLocator solves the issue.

**Comment by ewquon** [comment]
Okay. I think there's a matplotlib issue between your version and mine, because my plots hide the minor tick label when there's a major tick label, e.g., 0000 and 1200 above the date labels. I'll play around with it a bit today.

**Comment by ewquon** [comment]
Confirmed that this is a change in matplotlib behavior at some point between 3.0.3 to 3.1.1

MWE:
```
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import pandas as pd
time = pd.date_range(start='2013-11-08 12:00',end='2013-11-09 12:00',freq='10min')
u = pd.Series(np.random.random_sample(len(time)), index=time)
fig,ax = plt.subplots()
ax.plot(u.index, u)
ax.set_xlim((time[0],time[-1]))
ax.xaxis.set_minor_locator(mdates.HourLocator(byhour=range(24),interval=3))
ax.xaxis.set_minor_formatter(mdates.DateFormatter('%H%M'))
ax.xaxis.set_major_locator(mdates.AutoDateLocator(minticks=2,maxticks=3))
ax.xaxis.set_major_formatter(mdates.DateFormatter('\n%Y-%m-%d'))
```
image
image

**Comment by ewquon** [comment]
Plotting library can be remedied with this solution: https://stackoverflow.com/questions/57927519/matplotlib-display-minor-ticks-and-major-ticks-at-the-same-axis-location

**Pull request merged**
